name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
         docker build . --file Dockerfile -t mohamedhamedy/my-image
         docker tag mohamedhamedy/my-image mohamedhamedy/my-image:a
         docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
         docker push  mohamedhamedy/my-image:a
